### ISSUE TITLE
Replace the default dark code highlight style with a lighter version

### ISSUE THREAD

**Issue by SatnamSinghUK** [NHS-digital-website/design-system#134]
The code highlight class at the moment has a dark background and light text.

A ticket has been created to create a lighter version:
https://nhsd-jira.digital.nhs.uk/browse/DW-2503

However, would it not be more consistent to replace the dark style with the lighter version, so there is only one global class in total.

As at the moment DW-2503 will mean we have 2 classes, one for dark and one for light.

Satnam and Mark had a brief meeting on 31/8/21 around this, where the outcome was to create this idea/request as an issue which this is.

**Comment by buddieup** [comment]
Thanks for your contribution @SatnamSinghUK. The light version of the code snippet is live and you can view the documentation here: https://design-system.digital.nhs.uk/storybook/latest/?path=/docs/design-system-components-atoms-text-highlight--text-highlight-demo-2

To make the light version default, we would need to see evidence from user research that suggests the light version is easier to read and use. If you are able to provide the research and evidence, we will be more than happy to review.

**Comment by LEJA3** [comment]
I see no reason not to support both a light and dark variant of this token. This comes down to a UX decision about which should be default (and therefore the preferred) variant, and without a good reason for changing the current default I wouldn't want to needlessly introduce a change which could impact projects using the existing tokens.

Closing for now. We can revisit this if there's UX input.
